---
# tasks file for roles/configure-jenkins-master-container

- name: Run jenkins master container
  community.docker.docker_container:
    name: jenkins-master
    image: anas1243/jenkins-with-docker
    ports:
      - 8080:8080
      - 5000:5000
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart_policy: always
  notify: Generate ssh key-pairs inside jenkins-master

# Force run handlers to Generate ssh key-pairs inside the jenkins-master
- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Copy public key into the host
  ansible.builtin.command:
    cmd: docker cp jenkins-master:/var/jenkins_home/.ssh/id_rsa.pub .
  changed_when: false
