---
- name: Configure Jenkins master and Jenkins slave on docker containers
  hosts: jenkins-master
  roles:
    - configure-jenkins-master-container
    - configure-jenkins-slave-container

- name: Configure Jenkins slave on the EC2
  hosts: jenkins-slave
  roles:
    - configure-jenkins-slave-on-ec2
